# Spring Boot は自動的にこの application.yml ファイルを読み込める
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fa
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
  # Spring boot の i18n 対応：https://qiita.com/thrakt/items/135569e304f18f4fafe9
  messages:
    fallback-to-system-locale: false
    # properties ファイルの位置
    basename:  i18n/templates, i18n/templates_moviesample,i18n/templates_resipe_ishikawa,i18n/template_drink_yoshimoto,
        i18n/templates_tokyo_takehara,i18n/template_perfume_anzai,i18n/template_penguin_kawamura,i18n/templates_triathlon_mori,i18n/template_dog_kanno
        ,i18n/templates_drama_ige,i18n/templates_player_kuramoto,i18n/template_nbaplayers_takahashi,i18n/templates_vtuber_umehara,i18n/template_anime_watanabe,i18n/template_game_miura,i18n/templates_weapon_hiratsuka
    
    
  thymeleaf:
    # Thymeleaf のキャッシュが効いていると変更したあと即反映されません。開発時にはキャッシュを false にしておきます。
    cache: false

logging:
  level:
    # ログのレベルを設定
    # https://qiita.com/NagaokaKenichi/items/7cf2f427d88dfd4f56a8
    root: WARN
    org.hibernate: DEBUG
    org.springframework.web: DEBUG